name: PR Checks
on: [push, pull_request]

jobs:
  verify-pr:
    name: Verify PR
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Compile and build are ran on install

      - name: Unit Tests
        working-directory: packages/vite-plugin-web-extension
        run: pnpm test

      # - name: E2E Tests
      #   working-directory: packages/e2e
      #   run: pnpm test
